class IPacketParser():
    def parse(): ...
    
class IPacket():
    def set_destination_mac_ip(): ...
    def get_destination_mac_ip(): ...
    def get_source_mac_ip(): ...
    def set_source_mac_ip(): ...
    def get_raw_payload(): ...
    def set_raw_payload(): ...
    def get_ether_type(): ...
    def set_ether_type(): ...
    def set_checksum(): ...
    def get_checksum(): ...


class IInternetPacket():
    def get_version(): ...
    def set_version(): ...
    def get_ihl(): ...
    def set_ihl(): ...
    def get_tos(): ...
    def set_tos(): ...
    def get_total_length(): ...
    def set_total_length(): ...
    def get_identification(): ...
    def set_identification(): ...
    def get_ttl(): ...
    def set_ttl(): ...
    def get_protocol(): ...
    def set_protocol(): ...
    def get_header_checksum(): ...
    def set_header_checksum(): ...
    def get_source_ip(): ...
    def set_source_ip(): ...
    def get_dest_ip(): ...
    def set_dest_ip(): ...
    def get_payload(): ...
    def set_payload(): ...
