class IPacketParser():
    def parse(): ...
    
class IPacket():
    def set_destination_mac_ip(): ...
    def get_destination_mac_ip(): ...
    def get_source_mac_ip(): ...
    def set_source_mac_ip(): ...
    def get_raw_payload(): ...
    def set_raw_payload(): ...
    def get_ether_type(): ...
    def set_ether_type(): ...
