class ISniffer():
    def setup_sniffer(): ...
    def run(): ...
    def start_worker(): ...
    def process(): ...
    def on(): ...
    def add_event_listener(): ...
    def remove_event_listener(): ...
    def trigger_event(): ...
    def setup_logger(): ...
    